#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

vpn() {
    /opt/cisco/secureclient/bin/vpn "$@"
}

action="${1:-connect}"

case $action in
    connect)
        vpn connect fjernadgang.aarhuskommune.dk
        ;;
    disconnect)
        vpn disconnect
        ;;
    *)
        (>&2 echo "Usage: $0 [disconnect]")
        exit 1
        ;;
esac
